// <auto-generated />
namespace wepApiProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class init_productCart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init_productCart));
        
        string IMigrationMetadata.Id
        {
            get { return "202104071859555_init_productCart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
